# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c212154ff7675899fb4b28f52b60d079f70301aa853854ee739ec33194411965b232988c648f481162acb712b8542140021bdb65fcfd1e112dce9b8f5c38eb

test:
  secret_key_base: 93ac325dfd80c75c10d2744fd025d83c64f756b69d223e1d8645727f65f5173ec02cf6575bd95b220f6d1f19cb9af598ffffe7fa3ffb8fccf02bb0a8c262b123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
